### ISSUE TITLE
Nickname in use error not received when already that nickname.

### ISSUE THREAD

**Issue by realJoshByrnes** [ozjd/IRC2017#22]
--> NICK >Guest_a9b6df97
<-- :>Guest_a9b6df97!~IRCSock@host NICK >Guest_a9b6df97

I'm sure this should be a ERR_NICKNAMEINUSE candidate.

**Comment by jyonxo** [comment]
Correct response is no output (as per exchange behavior. I will fix this:

-> organisa-e679d0 NICK :Sky
<- :JD!~_______________________________@127.0.0.1 NICK :Sky
-> organisa-e679d0 NICK :Sky
-> organisa-e679d0 NICK :Sky

**Comment by realJoshByrnes** [comment]
That would make more sense! ~JD

**Comment by jyonxo** [comment]
Fixed as above however as discussed we are leaving room for case sensitive changes as they are important
