### ISSUE TITLE
Incorrect mode behaviour

### ISSUE THREAD

**Issue by Liam0306** [ozjd/IRC2017#23]
User had no other modes, server sends -q when it shouldn't.

-> TK2CHATCHATA01 MODE %#The\bLobby -o >Skyweb_92994
<- :'LÑÐ°Ð¼!~Sysop_Cascade@cg MODE %#The\bLobby -q >Skyweb_92994
<- :'LÑÐ°Ð¼!~Sysop_Cascade@cg MODE %#The\bLobby -o >Skyweb_92994

Is the same if you +o or -o, other modes (-q,+q,+v,-v) seem fine i think, only should be sending -q if the user had owner.

**Comment by jyonxo** [comment]
Bug occurred if an IRCOp level deops another user. It would consider if the IRCOp was admin, and then set -q accordingly to TargetUser.

Fix was to change IRCOp user to TargetUser in conditional if statement
