### ISSUE TITLE
show RealName in Whois

### ISSUE THREAD

**Issue by godzhand** [ozjd/IRC2017#25]
show the RealName e.g. the part at end of USER   in the WHOIS

**Comment by jyonxo** [comment]
-> TK2CHATCHATA01 WHOIS >Sky
<- :TK2CHATCHATA01 311 >Sky >Sky ~Admin_Sky static.88-198-62-147.clients.your-server.de * :test
<- :TK2CHATCHATA01 312 >Sky >Sky TK2CHATCHATA01 :
<- :TK2CHATCHATA01 671 >Sky >Sky :is using a secure connection
<- :TK2CHATCHATA01 317 >Sky >Sky 1 1504094333 :seconds idle, signon time
<- :TK2CHATCHATA01 318 >Sky >Sky :End of /WHOIS list

Ravi this works fine
