### ISSUE TITLE
Website to ask for nickname before joining channel (if one hasn't been set)

### ISSUE THREAD

**Issue by jyonxo** [ozjd/IRC2017#30]
At the moment we are giving random nicknames, this should be changed to someone having to set a nickname before joining the chat. Actually the WebChat already compensates for a random nickname.

**Comment by realJoshByrnes** [comment]
I'm going to add that cookies need to be updated at the time of change, or cookies need to be distributed in another way.

**Comment by jyonxo** [comment]
This is one for John but he needs to get registered before I can assign to him

**Comment by demirdjian** [comment]
Sign up page now asks for chat name and person's name.
