### ISSUE TITLE
SELF ACCESS (no privileges)

### ISSUE THREAD

**Issue by realJoshByrnes** [ozjd/IRC2017#6]
When attempting to add DENY ACCESS to self, it appears that users have no access to their own access list.

**Comment by realJoshByrnes** [comment]
Debug:
-> TK2CHATCHATA01 ACCESS JD ADD DENY >*!*@*$* 0 :Block guests from Whisper.
<- :TK2CHATCHATA01 913 JD JD :No access

As oper, it's apparently worse as it's successfully setting a NETWORK-WIDE ban
-> TK2CHATCHATA01 ACCESS >JD ADD DENY >*!*@*$* 0 :Block guests from Whisper.
<- :TK2CHATCHATA01 801 >JD * DENY >*!*@*$* 0 ~Admin_JD@cg :Block guests from Whisper.

**Comment by jyonxo** [comment]
Fixed Self Access, updated the AccessObjectName upon Nickname change
